#Define Project
substitutions:
  name: apollo-r-1
  version:  "24.3.1.1"
  device_description: ${name} made by Apollo Automation - version ${version}.
  
esphome:
  name: "${name}"
  friendly_name: Apollo R-1
  comment: Apollo R-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  on_boot:
  - priority: 900.0
    then:
      - lambda: |-
          id(cpu_speed) = ESP.getCpuFreqMHz();

  project:
    name: "ApolloAutomation.R-1"
    version: "${version}"

  min_version: 2024.2.0

# Define Board
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
  
dashboard_import:
  package_import_url: github://ApolloAutomation/R-1/Integrations/ESPHome/R-1.yaml
  import_full_config: false


globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"
  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'
  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'

# Enable Home Assistant API
# Also Add Buzzer Service Connection
api:
  on_client_connected:
    - delay: 1s
    - light.turn_off: green_led
    - lambda: 'id(cycleCounter) = 30;'
  services:
    - service: play_buzzer
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'

logger:

ota:
  password: "apolloautomation"
  safe_mode: false

wifi:

  power_save_mode: HIGH

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Apollo R1 Hotspot"

captive_portal:

improv_serial:

web_server:
  port: 80



# Buzzer
output:
  - platform: ledc
    pin: GPIO10
    id: buzzer
  - id: green_led_output
    platform: gpio
    pin: GPIO2

rtttl:
 output: buzzer



binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

  - platform: gpio
    pin:
      number: GPIO6
      mode:
        input: true
    name: LD012 Radar
    device_class: occupancy
    filters:
      - delayed_on: 100ms
      - delayed_off: 5s
  
  - platform: gpio
    pin: 
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
    id: reset_button
    on_press:
      then:
        - lambda: |-
            id(button_press_timestamp) = millis();
            
    on_release:
      then:
        - lambda: |-
            if (millis() - id(button_press_timestamp) >= 5000) {
              // Remove Wifi
              id(factory_reset_switch).turn_on();
              
            }

sensor:
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"
    id: esp_cpu_speed

  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature


  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all


switch:
  - platform: template
    name: "Startup Light Blink"
    id: startup_light_blink
    icon: mdi:lightbulb
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    entity_category: "config"

  - platform: factory_reset
    id: factory_reset_switch
    internal: true
  - platform: gpio
    name: "Power Control"
    id: power_control
    pin: GPIO5
  - platform: gpio
    pin:
      number: GPIO3  #Change the pin num to what you used
      mode:
        output: true
    name: LD012 Sensitivity Adjust
  
light:
  - platform: binary
    id: green_led
    name: "Green LED"
    output: green_led_output



#Used To Control RGB Light On Startup. Tells User Status Of Device
interval:
  - interval: 1s
    then:
      - if:
          condition:
            - binary_sensor.is_off: ink_ha_connected
            - lambda: 'return id(cycleCounter) < 30;'
            - switch.is_on: startup_light_blink

          then:
            - light.toggle:
                id: green_led
            - lambda: 'id(cycleCounter) += 1;'

  - interval: 1s
    then:
      - if:
          condition:
            - binary_sensor.is_off: ink_ha_connected
            - lambda: 'return id(cycleCounter) > 30;'
            - lambda: 'return id(cycleCounter) < 31;'
            - switch.is_on: startup_light_blink

          then:
            - light.turn_off:
                id: green_led
            - lambda: 'id(cycleCounter) += 1;'