#Define Project
substitutions:
  name: apollo-r-1
  version:  "24.3.1.1"
  device_description: ${name} made by Apollo Automation - version ${version}.
  
esphome:
  name: "${name}"
  friendly_name: Apollo R-1
  comment: Apollo R-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.R-1"
    version: "${version}"

  min_version: 2024.2.0
  on_boot:
    priority: 500
    then:
      - delay: 30s
      - if:
          condition:
            binary_sensor.is_off: ink_ha_connected
          then:
            - deep_sleep.enter: deep_sleep_1

# Define Board
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
  
external_components:
  - source: github://Option-Zero/esphome-components
    components: [max17048]

logger:
  level: NONE

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"
  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'
  - id: alarm_cycle
    restore_value: no
    type: int
    initial_value: "0"
  - id: alarm_string_value
    type: std::string
    restore_value: yes
    initial_value: '"ApolloAlarm:d=8,o=5,b=180:c,d,e,c,d,e,c,d,e,c,d,e,c,d,e,c,d,e,c,d,e;"'


ota:

wifi:
  power_save_mode: none
  ap:
    ssid: "Apollo R1 Hotspot"

mqtt:
  id: mqtt_connection
  broker: 10.69.3.113
  username: HA-MQTT
  password: "ZsHzZ@L37AkkhXyLQZ74GdWKGF_zfC"
  birth_message:
  will_message:
  on_message:
    # Prevent deep sleep for OTA
    - topic: apollo/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: apollo/sleep
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1

captive_portal:


i2c:
  sda: GPIO1
  scl: GPIO0
  id: bus_a

# Buzzer
output:
  - platform: ledc
    pin: GPIO10
    id: buzzer
  - id: red_led_output
    platform: gpio
    pin: GPIO2
rtttl:
 output: buzzer

deep_sleep:
  run_duration:
    default: 15s
    gpio_wakeup_reason: 15s
  sleep_duration: 24h
  wakeup_pin:
    number: GPIO3
    mode: INPUT_PULLUP
    inverted: false
  id: deep_sleep_1
  wakeup_pin_mode: KEEP_AWAKE


binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

  - platform: gpio
    pin:
      number: GPIO4
    name: "Presence Detected"
    id: presenceDetected
    device_class: occupancy
    filters:
      - delayed_on: 10ms  # Debounce filter to prevent false positives
      - delayed_off: 5s
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: presenceDetected
              - switch.is_on: alarm_switch

            then:
              - script.execute: sound_alarm
  
  - platform: gpio
    pin: 
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
    id: reset_button
    on_press:
      then:
        - lambda: |-
            id(button_press_timestamp) = millis();
            
    on_release:
      then:
        - lambda: |-
            if (millis() - id(button_press_timestamp) >= 5000) {
              // Remove Wifi
              id(factory_reset_switch).turn_on();
              
            }

sensor:
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"
    id: esp_cpu_speed

  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: max17048
    battery_voltage:
      name: Battery voltage
    battery_level:
      name: Battery level
    rate:
      name: Battery discharge rate
    

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all


switch:
  - platform: factory_reset
    id: factory_reset_switch
    internal: true
  - platform: template
    name: "Alarm"
    id: alarm_switch
    icon: mdi:siren
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: "config"
    optimistic: true

  
light:
  - platform: binary
    id: red_led
    name: "Red LED"
    output: red_led_output

text_sensor:
  - platform: template
    name: "Alarm String"
    id: alarm_string
    icon: mdi:note
    lambda: |-
      return id(alarm_string_value);
    entity_category: "config"
    on_value:
      then:
        - lambda: id(alarm_string_value) = x;
    
script:
  - id: sound_alarm
    then:
      - while:
          condition:
            # Presence Detected
            - binary_sensor.is_on: presenceDetected
            # Alarm is on
            - switch.is_on: alarm_switch
            - lambda: |-
                return id(alarm_cycle) < 3;
          then:
            - rtttl.play: !lambda 'return id(alarm_string_value).c_str();'
            - lambda: "id(alarm_cycle) += 1;"
            - delay: 1s
            
      