#Define Project
substitutions:
  name: apollo-r-1
  version:  "24.3.1.1"
  device_description: ${name} made by Apollo Automation - version ${version}.
  
esphome:
  name: "${name}"
  friendly_name: Apollo R-1
  comment: Apollo R-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio



  project:
    name: "ApolloAutomation.R-1"
    version: "${version}"

  min_version: 2024.2.0

# Define Board
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
  
dashboard_import:
  package_import_url: github://ApolloAutomation/R-1/Integrations/ESPHome/R-1.yaml
  import_full_config: false


globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"
  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'
  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'

# Enable Home Assistant API
# Also Add Buzzer Service Connection
api:
  services:
    - service: play_buzzer
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'


ota:

wifi:
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Apollo R1 Hotspot"

captive_portal:


#TODO: Prevent Deep Sleep Until Connected To HA (Or set period of time)
#TODO: Switch to control deep sleep
#TODO: Add MAX17048G Fuel Gauge & Control Hibernate State



# Buzzer
output:
  - platform: ledc
    pin: GPIO10
    id: buzzer
  - id: red_led_output
    platform: gpio
    pin: GPIO3
rtttl:
 output: buzzer

deep_sleep:
  run_duration:
    default: 30s
    gpio_wakeup_reason: 30s
  sleep_duration: 24h
  wakeup_pin:
    number: GPIO4
    mode: INPUT_PULLUP
    inverted: false
    allow_other_uses: true
  id: deep_sleep_1
  wakeup_pin_mode: KEEP_AWAKE


binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

  - platform: gpio
    pin:
      number: GPIO4
      allow_other_uses: true
    name: "Presence Detected"
    device_class: occupancy
    # Assuming the sensor pulls the pin HIGH when motion is detected; adjust if necessary
    filters:
      - delayed_on: 10ms  # Debounce filter to prevent false positives
      - delayed_off: 5s
  
  - platform: gpio
    pin: 
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
    id: reset_button
    on_press:
      then:
        - lambda: |-
            id(button_press_timestamp) = millis();
            
    on_release:
      then:
        - lambda: |-
            if (millis() - id(button_press_timestamp) >= 5000) {
              // Remove Wifi
              id(factory_reset_switch).turn_on();
              
            }

sensor:
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"
    id: esp_cpu_speed

  - platform: internal_temperature
    name: "ESP Temperature"
    id: sys_esp_temperature


  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all


switch:
  - platform: template
    name: "Startup Light Blink"
    id: startup_light_blink
    icon: mdi:lightbulb
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    entity_category: "config"

  - platform: factory_reset
    id: factory_reset_switch
    internal: true

  
light:
  - platform: binary
    id: red_led
    name: "Red LED"
    output: red_led_output
number:
  - platform: template
    name: Run Duration
    id: run_duration
    restore_value: true
    initial_value: 10
    min_value: 1.0
    max_value: 10000.0
    entity_category: "CONFIG"
    unit_of_measurement: seconds
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box

        
  - platform: template
    name: Sleep Duration
    id: sleep_duration
    restore_value: true
    initial_value: 480
    min_value: 1.0
    max_value: 10000.0
    entity_category: "CONFIG"
    unit_of_measurement: minutes
    optimistic: true
    update_interval: never
    step: 0.1
    mode: box


