
esphome:
  name: "apollo-r-1-eth"
  friendly_name: Apollo R-1
  comment: Apollo R-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.R-1-ETH"
    version: "25.3.27"

  min_version: 2024.6.4
  
dashboard_import:
  package_import_url: github://ApolloAutomation/R-1/Integrations/ESPHome/R-1_ETH.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_managed

http_request:
  verify_ssl: true

safe_mode:

update:
  - platform: http_request
    id: update_http_request
    name: Firmware Update
    source: https://apolloautomation.github.io/R-1/firmware-e/manifest.json

logger:

ethernet:  
  type: W5500  
  clk_pin: GPIO10  
  mosi_pin: GPIO12 
  miso_pin: GPIO11
  cs_pin: GPIO9
  interrupt_pin: GPIO13
  reset_pin: GPIO14


packages:
  core: !include Core.yaml
