name: CI

on:
  pull_request:

jobs:
  label-check:
    name: Label Check
    uses: ApolloAutomation/Workflows/.github/workflows/label-check.yml@main
    
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - Integrations/ESPHome/R_PRO-1_ETH.yaml
          - Integrations/ESPHome/R_PRO-1_W.yaml
        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v6
        with:
          yaml-file: ${{ matrix.file }}